export default {
    ADD_USERS: 'ADD_USERS',
    ADD_USER: 'ADD_USER',
    ADD_POSTS: 'ADD_POSTS',
    ADD_POST: 'ADD_POST',
    ADD_ALBUMS: 'ADD_ALBUMS',
    ADD_PHOTOS: 'ADD_PHOTOS',
    ADD_ALBUM: 'ADD_ALBUM',
    ADD_COMMENTS: 'ADD_COMMENTS'
}